# https://github.com/noirotm/flvmeta/issues/32
include("${CMAKE_CURRENT_LIST_DIR}/../support/cli.cmake")

function(check_delay name expected)
  generate_fixture(input "${name}")
  # Missing width/height metadata gives exit 9 independently of audiodelay.
  assert_flvmeta_exit_code(9 output --check "${input}")
  string(FIND "${output}" "audiodelay should be ${expected}, got 42" found)
  if(found EQUAL -1 OR NOT output MATCHES "W80062")
    message(FATAL_ERROR "${name}: incorrect checker delay\n${output}")
  endif()
  set(rewritten "${input}.updated.flv")
  assert_flvmeta_exit_code(0 output --update "${input}" "${rewritten}")
  assert_flvmeta_exit_code(0 output --dump --json "${rewritten}")
  string(REGEX MATCH "\"audiodelay\" *: *([-+0-9.eE]+)" delay "${output}")
  if(NOT "${CMAKE_MATCH_1}" STREQUAL "${expected}")
    message(FATAL_ERROR "${name}: incorrect generated delay\n${output}")
  endif()
  remove_fixtures("${input}" "${rewritten}")
endfunction()

check_delay(positive 2147483.393)
check_delay(negative -2147483.393)
check_delay(cross-positive 0.001)
check_delay(cross-negative -0.001)
check_delay(maximum 4294967.295)
check_delay(minimum -4294967.295)
check_delay(zero 0)
check_delay(ordinary 1)
