include("${CMAKE_CURRENT_LIST_DIR}/../support/cli.cmake")

foreach(mode avc header-only)
  generate_fixture(input "${mode}")
  # The empty metadata lacks width and height, but computation must finish.
  assert_flvmeta_exit_code(9 output --check "${input}")
  if(NOT output MATCHES "E60077" OR NOT output MATCHES "E60078")
    message(FATAL_ERROR "${mode}: file information could not be computed\n${output}")
  endif()
  set(rewritten "${input}.updated.flv")
  assert_flvmeta_exit_code(0 output --update "${input}" "${rewritten}")
  assert_flvmeta_exit_code(0 output --dump --json "${rewritten}")
  if(mode STREQUAL "avc")
    if(NOT output MATCHES "\"width\" *: *320" OR NOT output MATCHES "\"height\" *: *240")
      message(FATAL_ERROR "Incorrect AVC dimensions\n${output}")
    endif()
  elseif(output MATCHES "\"(width|height)\" *:")
    message(FATAL_ERROR "Dimensions generated without a video payload\n${output}")
  endif()
  remove_fixtures("${input}" "${rewritten}")
endforeach()
